AWSTemplateFormatVersion: '2010-09-09'
# ------------------------------------------------------------#
# パラメータ
# ------------------------------------------------------------#
Parameters:
  UniqueName:
    Type: String
    Default: myenv
  PublicSubnet:
    Description: Output from vpc stack
    Type: String
# ------------------------------------------------------------#
# リソース
# ------------------------------------------------------------#
Resources:
# ------------------------------------------------------------#
# リソース：cloud9
# ------------------------------------------------------------#
  Cloud9Instance:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      AutomaticStopTimeMinutes: 30
      ConnectionType: CONNECT_SSH
      Description: "cloud9 for terraform environment"
      ImageId: amazonlinux-2-x86_64
      InstanceType: t2.micro # Required
      Name: !Sub ${UniqueName}-cloud9-terraform
      OwnerArn: !Sub arn:aws:iam::${AWS::AccountId}:user/Administrator #Cloud9上で実行したいIAMユーザーを指定
      # Repositories:
      #   Repositories #AWS CodeCommitのリポジトリを指定できます。
      SubnetId: !Ref PublicSubnet #vpcスタックで出力されている値を取得
      