AWSTemplateFormatVersion: 2010-09-09
Description: Step 2, CodeCommit (in Repository Account)
# ------------------------------------------------------------#
# パラメータ
# ------------------------------------------------------------#
Parameters:
  Prefix:
    Type: String
    Default: system
    Description: Prefix.
  ProductionAccountId:
    Description: Production Account ID
    MaxLength: 12
    MinLength: 12
    Type: String
  S3BucketArn:
    Description: Production Account S3 Bucket ARN for Artifact
    Type: String
  CmkArn:
    Description: Production Account CMK ARN
    Type: String
  CodeCommitRepositoryArn:
    Description: CodeCommit Repository Arn
    Type: String
  CodeCommitRepositoryName:
    Description: Repository Account CodeCommit Repository Name
    Type: String
  BranchName:
    Type: String
    Default: main

# ------------------------------------------------------------#
# ラベル
# ------------------------------------------------------------# 
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "common param"
        Parameters:
          - Prefix
          - ProductionAccountId
      -
        Label:
          default: "codepipeline param"
        Parameters:
          - S3BucketArn
          - CmkArn
      -
        Label:
          default: "codecommit param"
        Parameters:
          - CodeCommitRepositoryArn
          - CodeCommitRepositoryName
          - BranchName
# ------------------------------------------------------------#
# リソース
# ------------------------------------------------------------#
Resources:
# ------------------------------------------------------------#
# リソース：IAMロール(CodeWatchEventを実行)
# ------------------------------------------------------------#
  CloudwatchEventRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Prefix}-CloudWatchEventRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: CloudWatchEventsBus
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: events:PutEvents
                Resource: !Sub arn:aws:events:${AWS::Region}:${ProductionAccountId}:event-bus/default

  # CloudWatchEventの実行ルール
  AmazonCloudWatchEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - CodeCommit Repository State Change
        resources:
          - Fn::Join:
              - ''
              - - 'arn:aws:codecommit:'
                - !Ref 'AWS::Region'
                - ':'
                - !Ref 'AWS::AccountId'
                - ':'
                - !Ref CodeCommitRepositoryName
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceType:
            - branch
          referenceName:
            - !Ref BranchName
      Targets:
        - Arn: !Sub arn:aws:events:${AWS::Region}:${ProductionAccountId}:event-bus/default
          RoleArn: !GetAtt CloudwatchEventRole.Arn
          Id: codepipeline-AppPipeline
# ------------------------------------------------------------#
# リソース：IAMロール(productアカウントへの権限付与)
# ------------------------------------------------------------#
  CodeCommitRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${ProductionAccountId}:root
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: source
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  - !Sub ${S3BucketArn}/*
              - Effect: Allow
                Action:
                  - kms:DescribeKey
                  - kms:GenerateDataKey*
                  - kms:Encrypt
                  - kms:ReEncrypt*
                  - kms:Decrypt
                Resource:
                  - !Ref CmkArn
              - Effect: Allow
                Action:
                  - codecommit:GetBranch
                  - codecommit:GetCommit
                  - codecommit:UploadArchive
                  - codecommit:GetUploadArchiveStatus
                  - codecommit:CancelUploadArchive
                Resource:
                  - !Ref CodeCommitRepositoryArn
# ------------------------------------------------------------#
# 出力
# ------------------------------------------------------------#
Outputs:
  CodeCommitRoleOutput:
    Value: !GetAtt CodeCommitRole.Arn
    Description: CodeCommitRole Arn
    Export:
      Name: CodeCommitRoleArn-Output