AWSTemplateFormatVersion: 2010-09-09
Description: |
  this is route stack input other child-stack URL and Parameters

# ------------------------------------------------------------#
# ラベル
# ------------------------------------------------------------# 
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "the bucket stored stack"
        Parameters:
          - StoredStackS3BucketName
      -
        Label:
          default: "common param"
        Parameters:
          - UniqueName
      -
        Label:
          default: "vpc param"
        Parameters:
          - VpcCidr
          - PublicSubnetAvailabilityZone
          - PublicSubnetCidr
# ------------------------------------------------------------#
# パラメータ：共通
# ------------------------------------------------------------# 
Parameters: 
  StoredStackS3BucketName:
    Type: String
  UniqueName:
    Type: String
    Default: myenv
# ------------------------------------------------------------#
# パラメータ：vpc
# ------------------------------------------------------------# 
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
  PublicSubnetAvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: ap-northeast-1a
  PublicSubnetCidr:
    Type: String
    Default: 10.0.1.0/24
# ------------------------------------------------------------#
# リソース
# ------------------------------------------------------------#
Resources:
# ------------------------------------------------------------#
# リソース：vpc
# ------------------------------------------------------------#
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StoredStackS3BucketName}.s3.${AWS::Region}.amazonaws.com/cloud9-terraform-public-environment/vpc/vpc.yml
      Parameters:
        UniqueName: !Ref UniqueName
        VpcCidr: !Ref VpcCidr
        PublicSubnetAvailabilityZone: !Ref PublicSubnetAvailabilityZone
        PublicSubnetCidr: !Ref PublicSubnetCidr
# ------------------------------------------------------------#
# リソース：iam
# ------------------------------------------------------------#
  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StoredStackS3BucketName}.s3.${AWS::Region}.amazonaws.com/cloud9-terraform-public-environment/iam/iam.yml
      Parameters:
        UniqueName: !Ref UniqueName
# ------------------------------------------------------------#
# リソース：cloud9
# ------------------------------------------------------------#
  CLOUD9:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StoredStackS3BucketName}.s3.${AWS::Region}.amazonaws.com/cloud9-terraform-public-environment/cloud9/cloud9.yml
      Parameters:
        UniqueName: !Ref UniqueName
        PublicSubnet: 
          Fn::GetAtt:
            - VPC
            - Outputs.PublicSubnetOutput
